# Copyright (c) winTerm contributors.
# Licensed under the MIT license.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^[0-9a-fA-F]{40}$')]
    [string]$CommitSha,

    [Parameter(Mandatory)]
    [ValidatePattern('^\d{4}-\d{2}-\d{2}T')]
    [string]$BuildTimestamp,

    [Parameter()]
    [ValidatePattern('^[0-9]+$')]
    [string]$WorkflowRunId = '0'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$outputPath = Join-Path $repositoryRoot 'src\winterm\Branding\ReleaseMetadata.generated.h'

try
{
    $parsedTimestamp = [DateTimeOffset]::Parse(
        $BuildTimestamp,
        [Globalization.CultureInfo]::InvariantCulture,
        [Globalization.DateTimeStyles]::AssumeUniversal)
    $normalizedTimestamp = $parsedTimestamp.ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

    $content = @(
        '// Generated by scripts/winterm/generate-build-metadata.ps1. Do not commit.'
        '#pragma once'
        ''
        "#define WINTERM_BUILD_COMMIT_SHA L`"$($CommitSha.ToLowerInvariant())`""
        "#define WINTERM_BUILD_TIMESTAMP L`"$normalizedTimestamp`""
        "#define WINTERM_BUILD_WORKFLOW_RUN_ID L`"$WorkflowRunId`""
    )
    [System.IO.File]::WriteAllLines($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Generated release build metadata: $outputPath" -ForegroundColor Green
}
catch
{
    Write-Error "Build metadata generation failed: $($_.Exception.Message)"
    exit 1
}
