// Copyright (c) winTerm contributors.
// Licensed under the MIT license.

import "DockingAndLayoutViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass DockingAndLayout : Windows.UI.Xaml.Controls.Page
    {
        DockingAndLayout();
        DockingAndLayoutViewModel ViewModel { get; };
    }
}
