// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass AboutDialog : Windows.UI.Xaml.Controls.ContentDialog, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AboutDialog();

        String ApplicationDisplayName { get; };
        String ApplicationVersion { get; };
        String ReleaseDetails { get; };
        Windows.Foundation.Uri SourceCodeUri { get; };
        Windows.Foundation.Uri DocumentationUri { get; };
        Windows.Foundation.Uri ReleaseNotesUri { get; };
        Windows.Foundation.Uri PrivacyPolicyUri { get; };

        Boolean CheckingForUpdates { get; };
        Boolean UpdatesAvailable { get; };
    }
}
